// Local Cart
export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_CLEAR = 'CART_CLEAR'

// Shipping Address
export const SHIPPING_ADDRESS = 'SHIPPING_ADDRESS'

// Payment Method
export const PAYMENT_METHOD = 'PAYMENT_METHOD'

// Cart Product
export const CART_PRODUCT_REQUEST = 'CART_PRODUCT_REQUEST'
export const CART_PRODUCT_SUCCESS = 'CART_PRODUCT_SUCCESS'
export const CART_PRODUCT_FAIL = 'CART_PRODUCT_FAIL'
export const CART_PRODUCT_RESET = 'CART_PRODUCT_REEST'

export const CART_PRODUCT_QTY = 'CART_PRODUCT_QTY'
export const CART_PRODUCT_REMOVE = 'CART_PRODUCT_REMOVE'
export const CART_PRODUCT_INITIAL_QUANTITY = 'CART_PRODUCT_INITIAL_QUANTITY'
export const CHECKOUT_CART = 'CHECKOUT_CART'
