// ! Public Access

export const PUBLIC_FETCH_ALL_CATEGORY_REQUEST =
  'PUBLIC_FETCH_ALL_CATEGORY_REQUEST'
export const PUBLIC_FETCH_ALL_CATEGORY_SUCCESS =
  'PUBLIC_FETCH_ALL_CATEGORY_SUCCESS'
export const PUBLIC_FETCH_ALL_CATEGORY_FAIL = 'PUBLIC_FETCH_ALL_CATEGORY_FAIL'
export const PUBLIC_FETCH_ALL_CATEGORY_RESET = 'PUBLIC_FETCH_ALL_CATEGORY_RESET'

// ! Admin Access

export const PRIVATE_FETCH_ALL_CATEGORY_REQUEST =
  'PRIVATE_FETCH_ALL_CATEGORY_REQUEST'
export const PRIVATE_FETCH_ALL_CATEGORY_SUCCESS =
  'PRIVATE_FETCH_ALL_CATEGORY_SUCCESS'
export const PRIVATE_FETCH_ALL_CATEGORY_FAIL = 'PRIVATE_FETCH_ALL_CATEGORY_FAIL'
export const PRIVATE_FETCH_ALL_CATEGORY_RESET =
  'PRIVATE_FETCH_ALL_CATEGORY_RESET'
