// ! Private Access

export const MY_ORDER_LIST_REQUEST = 'MY_ORDER_LIST_REQUEST'
export const MY_ORDER_LIST_SUCCESS = 'MY_ORDER_LIST_SUCCESS'
export const MY_ORDER_LIST_FAIL = 'MY_ORDER_LIST_FAIL'
export const MY_ORDER_LIST_RESET = 'MY_ORDER_LIST_RESET'

// ! Admin Access

export const ALL_ORDER_LIST_REQUEST = 'ALL_ORDER_LIST_REQUEST'
export const ALL_ORDER_LIST_SUCCESS = 'ALL_ORDER_LIST_SUCCESS'
export const ALL_ORDER_LIST_FAIL = 'ALL_ORDER_LIST_FAIL'
export const ALL_ORDER_LIST_RESET = 'ALL_ORDER_LIST_RESET'
