// ! Public Constants

export const PUBLIC_FETCH_ALL_PRODUCT_REQUEST =
  'PUBLIC_FETCH_ALL_PRODUCT_REQUEST'
export const PUBLIC_FETCH_ALL_PRODUCT_SUCCESS =
  'PUBLIC_FETCH_ALL_PRODUCT_SUCCESS'
export const PUBLIC_FETCH_ALL_PRODUCT_FAIL = 'PUBLIC_FETCH_ALL_PRODUCT_FAIL'
export const PUBLIC_FETCH_ALL_PRODUCT_RESET = 'PUBLIC_FETCH_ALL_PRODUCT_RESET'

export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST'
export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS'
export const PRODUCT_TOP_FAIL = 'PRODUCT_TOP_FAIL'

// ! Private Constants

export const PRIVATE_FETCH_ALL_PRODUCT_REQUEST =
  'PRIVATE_FETCH_ALL_PRODUCT_REQUEST'
export const PRIVATE_FETCH_ALL_PRODUCT_SUCCESS =
  'PRIVATE_FETCH_ALL_PRODUCT_SUCCESS'
export const PRIVATE_FETCH_ALL_PRODUCT_FAIL = 'PRIVATE_FETCH_ALL_PRODUCT_FAIL'
export const PRIVATE_FETCH_ALL_PRODUCT_RESET = 'PRIVATE_FETCH_ALL_PRODUCT_RESET'
